"""
Sandboxed Card Script Executor

Each dashboard card is a self-contained Python script stored in GCS.
Execution flow:

  1. Download script from GCS (or regenerate if missing)
  2. Write to temp file (auto-deleted after execution)
  3. Run in subprocess with:
     - 15-second timeout (prevents API hangs)
     - Injected env vars (decrypted credentials only)
     - No access to app internals/DB/Redis
  4. Read stdout as JSON (single result object)
  5. Return typed result (TABLE/METRIC/AUDIT/LIST/ERROR)

Security model:
  - Subprocess isolation: no access to app state
  - Credentials env-var-only: never written to disk
  - Script source: generated by card_generator.py (not user-supplied)
  - Timeout + stdout size limit: prevents DoS/memory exhaustion
"""

from __future__ import annotations

import asyncio
import json
import logging
import os
import sys
import tempfile

logger = logging.getLogger(__name__)

# Execution limits
CARD_TIMEOUT = 15  # seconds
MAX_OUTPUT_BYTES = 2 * 1024 * 1024  # 2 MB


async def execute_card_script(
    script_content: str,
    env_vars: dict[str, str],
) -> dict:
    """
    Execute a card script in a sandboxed subprocess and return its result.

    The script must print a single JSON object to stdout as its last output.
    env_vars are injected as environment variables into the subprocess.

    Returns a typed result dict (card_type + data) on success,
    or an error dict on failure/timeout.
    """
    # Write script to a temp file
    with tempfile.NamedTemporaryFile(
        mode="w",
        suffix=".py",
        delete=False,
        encoding="utf-8",
    ) as f:
        f.write(script_content)
        script_path = f.name

    try:
        # Build subprocess environment — clean base + injected credentials
        proc_env = {
            "PATH": os.environ.get("PATH", "/usr/bin:/usr/local/bin"),
            "PYTHONPATH": os.environ.get("PYTHONPATH", ""),
            "HOME": os.environ.get("HOME", "/tmp"),
        }
        proc_env.update(env_vars)

        proc = await asyncio.create_subprocess_exec(
            sys.executable,
            script_path,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env=proc_env,
        )

        try:
            stdout_bytes, stderr_bytes = await asyncio.wait_for(
                proc.communicate(),
                timeout=CARD_TIMEOUT,
            )
        except TimeoutError:
            proc.kill()
            await proc.communicate()
            logger.warning("Card script timed out after %ds", CARD_TIMEOUT)
            return _error_result(
                "timeout",
                f"This card took longer than {CARD_TIMEOUT}s to load. "
                "The data source may be slow or unavailable. Try refreshing.",
            )

        if proc.returncode != 0:
            stderr_text = stderr_bytes.decode("utf-8", errors="replace")[:500]
            logger.warning("Card script exited %d: %s", proc.returncode, stderr_text)
            return _error_result(
                "script_error",
                "This card encountered an error while fetching live data. "
                "Your credentials may have expired — reconnect the platform to fix this.",
                detail=stderr_text,
            )

        # Parse stdout as JSON
        stdout_text = stdout_bytes[:MAX_OUTPUT_BYTES].decode("utf-8", errors="replace").strip()
        if not stdout_text:
            return _error_result("empty_output", "Card script returned no data.")

        # Find the last JSON object in stdout (scripts may print debug lines before it)
        result = _extract_json(stdout_text)
        if result is None:
            return _error_result(
                "parse_error",
                "Card script output could not be parsed. This is a bug — please contact support.",
            )

        # Validate it has a card_type
        if "card_type" not in result:
            return _error_result(
                "schema_error",
                "Card script returned data without a card_type. This is a bug.",
            )

        return result

    finally:
        try:
            os.unlink(script_path)
        except OSError:
            pass


def _extract_json(text: str) -> dict | None:
    """
    Extract the last valid JSON object from a string.
    Scripts may print log lines before the final JSON payload.
    """
    # Try the whole text first
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    # Try each line from the end
    lines = text.strip().splitlines()
    for line in reversed(lines):
        line = line.strip()
        if line.startswith("{") and line.endswith("}"):
            try:
                return json.loads(line)
            except json.JSONDecodeError:
                continue

    return None


def _error_result(error_type: str, message: str, detail: str = "") -> dict:
    return {
        "card_type": "ERROR",
        "error_type": error_type,
        "message": message,
        "detail": detail,
    }


async def execute_cards_parallel(
    cards: list[dict],  # list of {script_content, env_vars, card_meta}
    max_concurrent: int = 4,
) -> list[dict]:
    """
    Execute multiple card scripts concurrently with a semaphore cap.
    Returns results in the same order as input.
    """
    semaphore = asyncio.Semaphore(max_concurrent)

    async def _run_one(card: dict) -> dict:
        async with semaphore:
            result = await execute_card_script(
                card["script_content"],
                card["env_vars"],
            )
            # Attach card metadata for the renderer
            result["_card_id"] = card.get("card_id")
            result["_card_title"] = card.get("card_title")
            result["_platform"] = card.get("platform")
            result["_position"] = card.get("position", 0)
            return result

    tasks = [_run_one(c) for c in cards]
    return await asyncio.gather(*tasks)
